### PR TITLE
v1.0.0

### PR DESCRIPTION
**Pull request by Yu-jinKim**
- Allows annotation of a vcf using src_vcfs
- Prefix the fields transfered with EGGD
- Default suffix for the output is "custom_annotated"

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/3)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/3)* status: all files reviewed, 2 unresolved discussions (waiting on @Yu-jinKim)

___
*[src/vcf_annotator.sh, line 21 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/3#-MIF4Zqb5KmVN8RilPXn:-MIF4Zqb5KmVN8RilPXo:b-kdary8) ([raw file](https://github.com/eastgenomics/eggd_vcf_annotator/blob/d33c56229c844cddddcc215a570422d06e12682f/src/vcf_annotator.sh#L21)):*
> ```
> ····
> ```
whitespace
___
*[src/vcf_annotator.sh, line 51 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/3#-MIF4ezE6P0moHgZDFQ_:-MIF4ezF-daTj555WR7Y:bke9adc) ([raw file](https://github.com/eastgenomics/eggd_vcf_annotator/blob/d33c56229c844cddddcc215a570422d06e12682f/src/vcf_annotator.sh#L51)):*
> ```
> ········
> ```
whitespace

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/3)* status: all files reviewed, 2 unresolved discussions (waiting on @mattgarner)

___
*[src/vcf_annotator.sh, line 21 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/3#-MIF4Zqb5KmVN8RilPXn:-MN3PUmfDfdfksnYSNXM:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_annotator/blob/d33c56229c844cddddcc215a570422d06e12682f/src/vcf_annotator.sh#L21)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> ····
> ```
whitespace
</blockquote></details>

Done.
___
*[src/vcf_annotator.sh, line 51 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/3#-MIF4ezE6P0moHgZDFQ_:-MN3PV6d1OMTHKUH77RG:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_annotator/blob/d33c56229c844cddddcc215a570422d06e12682f/src/vcf_annotator.sh#L51)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> ········
> ```
whitespace
</blockquote></details>

Done.

**Comment by jethror1** [comment]
is this still needed? just realised it was still open and assigned to me...

**Comment by Yu-jinKim** [comment]
no idea, that was work started a year ago @mattgarner any thoughts?

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/3)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @jethror1, @mattgarner, and @Yu-jinKim)

___
*[src/vcf_annotator.sh, line 20 at r3](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/3#-MqZ5M9N6t-SK5Iz2lUn:-MqZ5M9N6t-SK5Iz2lUo:bs09w2v) ([raw file](https://github.com/eastgenomics/eggd_vcf_annotator/blob/6a1df9c8b66993a7a5412b39933393761f3fdcf0/src/vcf_annotator.sh#L20)):*
> ```Shell
> 
>     # Compile bcftools
>     tar xjf bcftools-1.14.tar.bz2
> ```

you can use the app assets in 001 that are precompiled to save you some time and remove the included files, i.e.:

```
"assetDepends": [
      {
        "name": "bedtools",
        "project": "project-Fkb6Gkj433GVVvj73J7x8KbV",
        "folder": "/app_assets/bedtools/bedtools_v2.30.0",
        "version": "2.30.0"
      },
      {
        "name": "htslib",
        "project": "project-Fkb6Gkj433GVVvj73J7x8KbV",
        "folder": "/app_assets/htslib/htslib_v1.14.0",
        "version": "1.14.0"
      }
    ]
```
___
*[src/vcf_annotator.sh, line 37 at r3](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/3#-MqZ5ZkK9or5l_Jp_tU_:-MqZ5ZkK9or5l_Jp_tUa:byyzi2f) ([raw file](https://github.com/eastgenomics/eggd_vcf_annotator/blob/6a1df9c8b66993a7a5412b39933393761f3fdcf0/src/vcf_annotator.sh#L37)):*
> ```Shell
> 
>     # Index both given vcfs
>     bcftools index --threads $nb_cpus ${raw_vcf_name}.gz
> ```

does it not default to using all threads?

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/3)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[src/vcf_annotator.sh, line 20 at r3](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/3#-MqZ5M9N6t-SK5Iz2lUn:-MqZTokd0czQT2sMbzD3:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_annotator/blob/6a1df9c8b66993a7a5412b39933393761f3fdcf0/src/vcf_annotator.sh#L20)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

you can use the app assets in 001 that are precompiled to save you some time and remove the included files, i.e.:

```
"assetDepends": [
      {
        "name": "bedtools",
        "project": "project-Fkb6Gkj433GVVvj73J7x8KbV",
        "folder": "/app_assets/bedtools/bedtools_v2.30.0",
        "version": "2.30.0"
      },
      {
        "name": "htslib",
        "project": "project-Fkb6Gkj433GVVvj73J7x8KbV",
        "folder": "/app_assets/htslib/htslib_v1.14.0",
        "version": "1.14.0"
      }
    ]
```
</blockquote></details>

Done.
___
*[src/vcf_annotator.sh, line 37 at r3](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/3#-MqZ5ZkK9or5l_Jp_tU_:-MqZ630o4yB742oqOMjB:b-fd3qzw) ([raw file](https://github.com/eastgenomics/eggd_vcf_annotator/blob/6a1df9c8b66993a7a5412b39933393761f3fdcf0/src/vcf_annotator.sh#L37)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

does it not default to using all threads?
</blockquote></details>

I think it does but only for indexing. So adding it everywhere

**Review by jethror1 — COMMENTED** [review]
are you intending to build this as an app? If so I'd add the developers to the json: https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/78ed75253c0b55a0dd38db9e7d555fec44d82dcb/dxapp.json#L434

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/3#-:-MqZgdaCByQdqwQZJYkX:b-dt4gdd)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @mattgarner)

**Review by jethror1 — APPROVED** [review]
> Reviewed 2 of 5 files at r3, 2 of 3 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/3)* status: all files reviewed, 2 unresolved discussions (waiting on @mattgarner)

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/3)* status: all files reviewed, 2 unresolved discussions (waiting on @mattgarner)

**Review by jethror1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/3#-:-MqZyDdFBqmmlBQUarOD:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @mattgarner)

**Review by mattgarner — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/3#-:-MqoDMqX1KIPejWV72Sc:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @mattgarner)

**Review by mattgarner — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
