### PR TITLE
bcftools norm corrected. Handle empty CSQ key. Reorganise sh script

### PR DESCRIPTION
**Pull request by mattgarner**
bcftools norm corrected. Handle empty CSQ key. Reorganised sh script

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/4)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/4)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @mattgarner and @Yu-jinKim)

___
*[src/vcf_annotator.sh, line 63 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/4#-MrMGVrNE36IVWc2_PiZ:-MrMGVrNE36IVWc2_Pi_:bu5a5e) ([raw file](https://github.com/eastgenomics/eggd_vcf_annotator/blob/697d140abdb5ad25b65a94b65ed98a946a57d9bf/src/vcf_annotator.sh#L63)):*
> ```Shell
> 
>     cat dest.vcf | \
>     # CSQ is 1st INFO field
> ```

minor thing but I find indentation and pipes at the beginning easier to read and more obvious its one series of pipes:
```
    cat dest.vcf \
        # CSQ is 1st INFO field
        | sed s/"\\tCSQ;"/"\\tCSQ=.;"/g \
        # CSQ is mid INFO field
        | sed s/";CSQ;"/";CSQ=.;"/g \
        # CSQ is last INFO field
        | sed s/";CSQ\\t"/";CSQ=.\t"/g \
        > csq_fix.vcf

    bgzip csq_fix.vcf

``` 



_Code quote:_
```Shell
    cat dest.vcf | \
    # CSQ is 1st INFO field
    sed s/"\\tCSQ;"/"\\tCSQ=.;"/g | \
    # CSQ is mid INFO field
    sed s/";CSQ;"/";CSQ=.;"/g | \
    # CSQ is last INFO field
    sed s/";CSQ\\t"/";CSQ=.\t"/g \
    > csq_fix.vcf
    bgzip csq_fix.vcf
```
___
*[src/vcf_annotator.sh, line 76 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/4#-MrMHybr-Tn0ycGIFONN:-MrMHybs-ghfVO_QbfQc:bzbouh2) ([raw file](https://github.com/eastgenomics/eggd_vcf_annotator/blob/697d140abdb5ad25b65a94b65ed98a946a57d9bf/src/vcf_annotator.sh#L76)):*
> ```Shell
>     annotated_vcf_file=${basename}_${output_suffix}.vcf.gz
> 
>     # Decompose/normalise/left align raw vcf, bgzip output
> ```

are we certain the annotating vcf is normalised? should we do it here to ensure both vcfs are the same?
___
*[src/vcf_annotator.sh, line 94 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/4#-MrMHGjz6vNJd2Dkn6Kp:-MrMHGk-3AuMUvnBUb76:b32x0h) ([raw file](https://github.com/eastgenomics/eggd_vcf_annotator/blob/697d140abdb5ad25b65a94b65ed98a946a57d9bf/src/vcf_annotator.sh#L94)):*
> ```Shell
>     #  output vcf in addition to the requested annotation.
>     #
>     # PL for the called genotype is 0 in the input vcf, however for 
> ```

ws
___
*[src/vcf_annotator.sh, line 95 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/4#-MrMHHld9rB229sT6lR1:-MrMHHle8gwozVsa2ilF:b32x0h) ([raw file](https://github.com/eastgenomics/eggd_vcf_annotator/blob/697d140abdb5ad25b65a94b65ed98a946a57d9bf/src/vcf_annotator.sh#L95)):*
> ```Shell
>     #
>     # PL for the called genotype is 0 in the input vcf, however for 
>     #  multi-allelic calls this information is lost during the split/merge 
> ```

ws
___
*[src/vcf_annotator.sh, line 96 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/4#-MrMHIY3DE9ycLLBtiC0:-MrMHIY3DE9ycLLBtiC1:b-od50do) ([raw file](https://github.com/eastgenomics/eggd_vcf_annotator/blob/697d140abdb5ad25b65a94b65ed98a946a57d9bf/src/vcf_annotator.sh#L96)):*
> ```Shell
>     # PL for the called genotype is 0 in the input vcf, however for 
>     #  multi-allelic calls this information is lost during the split/merge 
>     #  operation since no single vcf record contains the called genotype 
> ```

https://marketplace.visualstudio.com/items?itemName=shardulm94.trailing-spaces

**Review by Yu-jinKim — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/4)* status: all files reviewed, 5 unresolved discussions (waiting on @mattgarner)

**Review by mattgarner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/4)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[src/vcf_annotator.sh, line 63 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/4#-MrMGVrNE36IVWc2_PiZ:-MrO7XbB-ODZ0cylKlup:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_vcf_annotator/blob/697d140abdb5ad25b65a94b65ed98a946a57d9bf/src/vcf_annotator.sh#L63)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

minor thing but I find indentation and pipes at the beginning easier to read and more obvious its one series of pipes:
```
    cat dest.vcf \
        # CSQ is 1st INFO field
        | sed s/"\\tCSQ;"/"\\tCSQ=.;"/g \
        # CSQ is mid INFO field
        | sed s/";CSQ;"/";CSQ=.;"/g \
        # CSQ is last INFO field
        | sed s/";CSQ\\t"/";CSQ=.\t"/g \
        > csq_fix.vcf

    bgzip csq_fix.vcf

``` 
</blockquote></details>

Done
___
*[src/vcf_annotator.sh, line 76 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/4#-MrMHybr-Tn0ycGIFONN:-MrO7xwoELl8uR-obXtg:bq03zcu) ([raw file](https://github.com/eastgenomics/eggd_vcf_annotator/blob/697d140abdb5ad25b65a94b65ed98a946a57d9bf/src/vcf_annotator.sh#L76)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

are we certain the annotating vcf is normalised? should we do it here to ensure both vcfs are the same?
</blockquote></details>

I considered it, but removed it since it was increasing the run time/cost considerably to run norm on the gnomad vcf each time.

It is specified in dxapp.json that this vcf must be decomposed/normalised/left-aligned, but this is not enforced. I've also updated to readme to make this explicit.

As this will only be used in a workflow where this input is passed automatically from upstream apps I'm inclined to normalise src outside this app unless you are strongly opposed to this.
___
*[src/vcf_annotator.sh, line 94 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/4#-MrMHGjz6vNJd2Dkn6Kp:-MrO7brA-TTnEiAk0O0a:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_vcf_annotator/blob/697d140abdb5ad25b65a94b65ed98a946a57d9bf/src/vcf_annotator.sh#L94)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

ws
</blockquote></details>

Done
___
*[src/vcf_annotator.sh, line 95 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/4#-MrMHHld9rB229sT6lR1:-MrO7eNSCg5KEASqUjYN:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_vcf_annotator/blob/697d140abdb5ad25b65a94b65ed98a946a57d9bf/src/vcf_annotator.sh#L95)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

ws
</blockquote></details>

Done
___
*[src/vcf_annotator.sh, line 96 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/4#-MrMHIY3DE9ycLLBtiC0:-MrO7gVO0Fv7iqFknERw:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_vcf_annotator/blob/697d140abdb5ad25b65a94b65ed98a946a57d9bf/src/vcf_annotator.sh#L96)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

https://marketplace.visualstudio.com/items?itemName=shardulm94.trailing-spaces
</blockquote></details>

Done

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/4)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @jethror1, @mattgarner, and @Yu-jinKim)

___
*[dxapp.json, line 6 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/4#-MrMIVkp0RwrOslIy-k6:-MrMIVkp0RwrOslIy-k7:bm04im5) ([raw file](https://github.com/eastgenomics/eggd_vcf_annotator/blob/697d140abdb5ad25b65a94b65ed98a946a57d9bf/dxapp.json#L6)):*
> ```JSON
>   "summary": "Using one source vcf, annotate another vcf",
>   "dxapi": "1.0.0",
>   "version": "1.1.0",
> ```

is this going to be an app or applet? is it redundant to have version and version in the name?
___
*[src/vcf_annotator.sh, line 76 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/4#-MrMHybr-Tn0ycGIFONN:-MrO9_XxEhPlp7vC9kPu:b-vqcbbc) ([raw file](https://github.com/eastgenomics/eggd_vcf_annotator/blob/697d140abdb5ad25b65a94b65ed98a946a57d9bf/src/vcf_annotator.sh#L76)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

I considered it, but removed it since it was increasing the run time/cost considerably to run norm on the gnomad vcf each time.

It is specified in dxapp.json that this vcf must be decomposed/normalised/left-aligned, but this is not enforced. I've also updated to readme to make this explicit.

As this will only be used in a workflow where this input is passed automatically from upstream apps I'm inclined to normalise src outside this app unless you are strongly opposed to this.
</blockquote></details>

that's fair, that's on us to just make sure we normalise

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/4)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @jethror1, @mattgarner, and @Yu-jinKim)

**Pull request merged**
