### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by Yu-jinKim**
I'm not sure how to call the output files, if you have any input on that

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/1)

### CODE REVIEW

**Comment by Yu-jinKim** [comment]
Jethro made me realize something. Bcftools only adds the annotation if the position, ref and alt are identical between the 2 vcfs and that might be not enough.

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 1 of 1 files at r2, 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/1)* status: all files reviewed, 5 unresolved discussions (waiting on @Yu-jinKim)

___
*[dxapp.json, line 6 at r3](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/1#-ME70DAn36sqoAVvKN1U:-ME70DAo7dldfY-ZEOLs:bxxfoh2) ([raw file](https://github.com/eastgenomics/eggd_vcf_annotator/blob/9362e3b6cd49fcc8117e3d2ce63d35f8b430430a/dxapp.json#L6)):*
> ```JSON
>   "summary": "Using one source vcf, annotate another vcf.",
>   "dxapi": "1.0.0",
>   "version": "1.0.0",
> ```

Needs the github release section
___
*[Readme.md, line 8 at r3](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/1#-ME71ceZ9IyiPCBUTNBI:-ME71ceZ9IyiPCBUTNBJ:bfowbno) ([raw file](https://github.com/eastgenomics/eggd_vcf_annotator/blob/9362e3b6cd49fcc8117e3d2ce63d35f8b430430a/Readme.md#L8)):*
> ```Markdown
> 
> ## What are typical use cases for this app?
> This app may be executed as a standalone app.
> ```

Describing an example use case here would be useful
e.g. adding clinvar annotation to a patient vcf
___
*[Readme.md, line 12 at r3](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/1#-ME71x6eCYTbf2h3C4SX:-ME71x6eCYTbf2h3C4SY:b-43qxt9) ([raw file](https://github.com/eastgenomics/eggd_vcf_annotator/blob/9362e3b6cd49fcc8117e3d2ce63d35f8b430430a/Readme.md#L12)):*
> ```Markdown
> ## What data are required for this app to run?
> This app requires 2 VCFs and a string to run.  
> The first vcf is the one you want to annotate, the second is the VCF containing the annotation. The fields input is comma-separated string to specify which columns to annotate with.  
> ```

columns or fields (or both)? i.e. info is a column, but you can pull out individual fields from it according to the tags provided
___
*[Readme.md, line 13 at r3](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/1#-ME72dN15lcStgpzJlfy:-ME72dN15lcStgpzJlfz:bqjmkun) ([raw file](https://github.com/eastgenomics/eggd_vcf_annotator/blob/9362e3b6cd49fcc8117e3d2ce63d35f8b430430a/Readme.md#L13)):*
> ```Markdown
> This app requires 2 VCFs and a string to run.  
> The first vcf is the one you want to annotate, the second is the VCF containing the annotation. The fields input is comma-separated string to specify which columns to annotate with.  
> Be sure that the src_vcf is bgzipped using:
> ```

Inconsistent with the dxapp.json which allows .vcf as input. Could we have the app bgzip input .vcfs if they are not already bgzipped?
___
*[src/vcf_annotator.sh, line 30 at r3](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/1#-ME74vkR0MVeGIGgHYpO:-ME74vkR0MVeGIGgHYpP:b-pnlpqu) ([raw file](https://github.com/eastgenomics/eggd_vcf_annotator/blob/9362e3b6cd49fcc8117e3d2ce63d35f8b430430a/src/vcf_annotator.sh#L30)):*
> ```Shell
> 
>     basename=$(echo $raw_vcf_name | cut -d"." -f1)
>     annotated_vcf_file=${basename}_annotated.vcf
> ```

Can we add an optional string input which is this suffix, which defualts to "_annotated"? 
This allows us to change this as appropriate for the case and avoid things like "_annotated_annotated_annotated.vcf"

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/1)* status: all files reviewed, 5 unresolved discussions (waiting on @mattgarner and @Yu-jinKim)

___
*[Readme.md, line 13 at r3](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/1#-ME72dN15lcStgpzJlfy:-ME7B_R05HvAN1IG_XWk:b-tagvya) ([raw file](https://github.com/eastgenomics/eggd_vcf_annotator/blob/9362e3b6cd49fcc8117e3d2ce63d35f8b430430a/Readme.md#L13)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Inconsistent with the dxapp.json which allows .vcf as input. Could we have the app bgzip input .vcfs if they are not already bgzipped?
</blockquote></details>

One issue I found is that bgzipped files do not necessarily have .bz2 extension and bgzipping the src_vcf is really
 slow for the gnomAD vcf (5.1 Go). So i choose to only bgzip the raw vcf and have the src_vcf which will be controlled by us already bgzipped.

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/1)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @mattgarner)

___
*[dxapp.json, line 6 at r3](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/1#-ME70DAn36sqoAVvKN1U:-ME7YU-lDVxAWOSTXWKE:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_annotator/blob/9362e3b6cd49fcc8117e3d2ce63d35f8b430430a/dxapp.json#L6)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Needs the github release section
</blockquote></details>

Done.
___
*[Readme.md, line 8 at r3](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/1#-ME71ceZ9IyiPCBUTNBI:-ME7YVMB885KEePRyW9y:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_annotator/blob/9362e3b6cd49fcc8117e3d2ce63d35f8b430430a/Readme.md#L8)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Describing an example use case here would be useful
e.g. adding clinvar annotation to a patient vcf
</blockquote></details>

Done.
___
*[Readme.md, line 12 at r3](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/1#-ME71x6eCYTbf2h3C4SX:-ME7YWBk-B0jLjnugbCH:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_annotator/blob/9362e3b6cd49fcc8117e3d2ce63d35f8b430430a/Readme.md#L12)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

columns or fields (or both)? i.e. info is a column, but you can pull out individual fields from it according to the tags provided
</blockquote></details>

Done.
___
*[src/vcf_annotator.sh, line 30 at r3](https://reviewable.io/reviews/eastgenomics/eggd_vcf_annotator/1#-ME74vkR0MVeGIGgHYpO:-ME7YXmu7OGcf7fd0_kk:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_annotator/blob/9362e3b6cd49fcc8117e3d2ce63d35f8b430430a/src/vcf_annotator.sh#L30)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Can we add an optional string input which is this suffix, which defualts to "_annotated"? 
This allows us to change this as appropriate for the case and avoid things like "_annotated_annotated_annotated.vcf"
</blockquote></details>

Done.

**Pull request closed without merging**
